settings:
    #seed: 1621433209
    game-speed: 2
    show-fog: true
    show-ui: true
    show-entity-overview: false
    game-time:
        initial: 0.06
        factors:
            night: 0.000024
            morning: 0.00002
            afternoon: 0.00002
            evening: 0.00002
        thresholds:
            max: 0.24
            morning: 0.06
            afternoon: 0.12
            evening: 0.17
            night: 0.2
    default-update-interval: 0.0015
    entity-visibility:
        entity-hunter-btn: true
        entity-rabbit-btn: true
        entity-wolf-btn: true
        entity-deer-btn: true
        entity-berry-bush-btn: true
berry-bush:
    spawn: 0.020
    update-interval: 1
    spawn-min-berries: 5
    spawn-max-berries: 10
    grow-min-berries: 1
    grow-max-berries: 2
    min-berry-limit: 12
    max-berry-limit: 20
berry:
    nutritional-value: 2
bedroll:
    comfort: 1.25
    wake-chance: 0
bow:
    accuracy: 0.9
    damage: 10
deer:
    spawn: 0.00033
    hunger-chance: 0.7
    sleep-in-chance: 0.7
    aggro-chance: 0.7
    herd-aggro-chance: 0.3
    max-health: 40
    starting-health: 40
    nutritional-value: 75
    roam-distance: 3
    attack-damage: 13
    vision-distance:
        morning: 5
        afternoon: 5
        evening: 5
        night: 4
    flee-search-attempts: 4
    flee-jitter-multiplier: 2
    action-cooldowns:
        default: 0.0015
        movement-action: 0.0011
        pursue-action: 0.0009
        flee-action: 0.0008
        scan-for-threats-action: 0.0001
        graze-action: 0.003
        attack-action: 0.0012
doe:
    leash: 3
    roam-distance: 1
    attack-damage: 5
    aggro-chance: 0.3
entity:
    max-recent-actions: 40
    min-recent-actions: 15
fire-pit:
    duration: 0.06
ground:
    sleep-comfort: 0.2
    sleep-health-gain: 0.05
    wake-chance: 0.1
hunter:
    x-spawn: 47
    y-spawn: 10
    vision-distance:
        morning: 4
        afternoon: 4
        evening: 3
        night: 1
    roam-distance: 8
    max-hunger: 50
    max-health: 50
    max-energy: 50
    starting-hunger: 30
    starting-health: 50
    starting-energy: 50
    hunger-loss: 0.18
    energy-loss: 0.25
    sleep-health-gain: 0.25
    starvation-health-loss: 0.5
    sleep-deprivation-health-loss: 0.1
    sleep-deprivation-chance-to-pass-out: 0.07
    hunger-threshold-low: 25
    hunger-threshold-high: 50
    tired-threshold: 15
    accuracy: 0.9
    attack-damage: 12
    max-path-distance: 12
    roam-candidates: 3
    bandage-threshold: 25
    bandage-heal-amount: 5
    camp:
        x-spawn: 49
        y-spawn: 10
    max-recent-actions: 100
    min-recent-actions: 30
    action-cooldowns:
        default: 0.0015
        movement-action: 0.0015
        search-area-action: 0.0021
rabbit:
    spawn: 0.01
    hunger-chance: 0.7
    sleep-in-chance: 0.7
    max-health: 5
    starting-health: 5
    nutritional-value: 15
    roam-distance: 3
    vision-distance:
        morning: 1
        afternoon: 1
        evening: 1
        night: 1
    action-cooldowns:
        default: 0.0015
        movement-action: 0.001
        graze-action: 0.002
wolf:
    spawn: 0.00027
    max-hunger: 75
    max-health: 30
    max-energy: 50
    starting-hunger: 25
    starting-health: 30
    starting-energy: 50
    hunger-loss: 0.1
    energy-loss: 0.20
    starvation-health-loss: 0.3
    sleep-deprivation-health-loss: 0.1
    sleep-deprivation-chance-to-pass-out: 0.07
    sleep-energy-gain: 1.6
    sleep-health-gain: 0.4
    sleep-in-chance: 0.2
    hunger-threshold: 30
    tired-threshold: 15
    nap-chance: 0.15
    need-a-snack-chance: 0.2
    roam-distance: 12
    attack-damage: 7
    vision-distance:
        morning: 5
        afternoon: 5
        evening: 4
        night: 3
    action-cooldowns:
        default: 0.0015
        movement-action: 0.0016
        pursue-action: 0.001
        search-area-action: 0.0016
